name: example
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vinyl:
    path: ../vinyl

dev_dependencies:
  build_runner:
  vinyl_generator:
    path: ../vinyl_generator
